# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3191540fcf89b82379f7803981f9020bcdaa39a9954053dcba7e87afa2ecd904c5a2d1e031b5bd100b647041b1e945e8bb8c0f713ac8ccbe2da0627142de574

test:
  secret_key_base: 6f1e6a418ae9ad656d1c53beb14fe7b0dcfc1b5f374577d4be9bf9ecefe733f25bb32bad8bcd57eb9b319d951671f26eb0c0265f17f469f72920622fe1664ec8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
